// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_get_version from "./routes/api/get_version.ts";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $thank_you from "./routes/thank_you.tsx";
import * as $Counter from "./islands/Counter.tsx";
import * as $DownloadButton from "./islands/DownloadButton.tsx";
import * as $Nav from "./islands/Nav.tsx";
import * as $NewsPopup from "./islands/NewsPopup.tsx";
import * as $scroll_reveal from "./islands/scroll_reveal.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/get_version.ts": $api_get_version,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
    "./routes/thank_you.tsx": $thank_you,
  },
  islands: {
    "./islands/Counter.tsx": $Counter,
    "./islands/DownloadButton.tsx": $DownloadButton,
    "./islands/Nav.tsx": $Nav,
    "./islands/NewsPopup.tsx": $NewsPopup,
    "./islands/scroll_reveal.tsx": $scroll_reveal,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
